# Generated by Django 5.2.3 on 2025-11-25 14:35

import uuid

import django.contrib.postgres.functions
import django.db.models.deletion
from django.db import migrations, models

import dreng.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskState",
            fields=[
                ("identifier", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50)),
                ("expires_at", models.DateTimeField()),
                ("data", models.JSONField(decoder=dreng.utils.JSONDecoder, encoder=dreng.utils.JSONEncoder, null=True)),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="dreng_tasks_expires_760d5d_idx")],
            },
        ),
        migrations.CreateModel(
            name="FailedJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task", models.CharField(max_length=255)),
                ("args", models.JSONField(decoder=dreng.utils.JSONDecoder, encoder=dreng.utils.JSONEncoder)),
                ("failed_at", models.DateTimeField()),
                ("failure_reason", models.CharField(max_length=100)),
                (
                    "job_id",
                    models.BigIntegerField(help_text="ID of the original Job instance. Stored for debugging purposes."),
                ),
                (
                    "state",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to="dreng.taskstate"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task", models.CharField(max_length=255)),
                ("args", models.JSONField(decoder=dreng.utils.JSONDecoder, encoder=dreng.utils.JSONEncoder)),
                ("created_at", models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                ("execute_at", models.DateTimeField(default=django.contrib.postgres.functions.TransactionNow)),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Jobs with higher priority will be processed first."),
                ),
                ("expire_at", models.DateTimeField(default=None, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("queue", models.CharField(max_length=50)),
                (
                    "state",
                    models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to="dreng.taskstate"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["execute_at"], name="dreng_job_execute_86a7cc_idx")],
            },
        ),
    ]
